### ISSUE TITLE
汉化问题

### ISSUE THREAD

**Issue by MoeHero** [UUUii/Reika_mods_Localization#2]
你们汉化的xml文件有问题，在最新版roc中会导致无法开启，请仔细检查下

**Comment by UUUii** [comment]
嗯好的，不过听说你有修复好的，不介意就pr到这吧

**Comment by 3TUSK** [comment]
@MoeHero 抱歉来迟了，不过可以确定应该是哪个人一不小心手残删掉了一个字母导致的。
https://github.com/UUUii/Reika_mods_Localization/blob/master/Rotarycraft/Resources/zh_CN/machines.xml#L1130

**Comment by 3TUSK** [comment]
@MoeHero @UUUii @IamAchang 
https://github.com/UUUii/Reika_mods_Localization/commit/9aa8e4636c028a1ae0e961e75e9f959c048db0ed#diff-f8231d962cb00873e185aef99331004dR1087
确定了，是手残删掉了...对此我们表示抱歉。

**Comment by MoeHero** [comment]
UUUii 是哪位…   你们也有不少没翻译以及和新版不对应的，还有一个就是不知为何中文依旧会导致加载失败，我自己弄出来了一个他加载的代码，可是貌似没问题，目前roc最新10b 我测试的是没法启动的

**Comment by MoeHero** [comment]
我有一份应该算改好的文件，明天我发个pr

**Comment by 3TUSK** [comment]
1.@UUUii 是那位我叫兰生
2.这个汉化大概是V7c还是什么时候做的，大概今年8月初以后就没再碰过，过时自然是可能的，如果愿意帮忙修复的话也是非常欢迎的。

**Comment by MoeHero** [comment]
已经提交pr了请通过谢谢

**Comment by IamAchang** [comment]
原来如此,看来是我当初汉化机器部分手滑了╮(╯▽╰)╭ 背锅背锅
